### ISSUE TITLE
缺失明确的许可证

### ISSUE THREAD

**Issue by Cai1Hsu** [os-module/visionfive2-sd#1]
您好，

非常感谢您分享这个优秀的开源项目！但是我注意到仓库中没有包含任何许可证文件。

根据开源社区的惯例，项目通常会附带一个许可证文件，以明确用户在使用、修改和分发代码时的权限和限制。没有明确的许可证文件可能会使潜在用户对如何合法使用您的代码感到困惑，并可能阻碍社区的进一步发展。

我建议在仓库中添加一个适当的开源许可证（例如 MIT, Apache 2.0, GPL 等），以便用户能够更清晰地了解使用条款。如果您不确定选择哪种许可证，您可以参考[选择开源许可证的指南](https://choosealicense.com/)。

**Comment by Godones** [comment]
感谢您的提醒，我已经增加了许可证文件。如果遇到问题欢迎反馈。
